-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Versión del servidor:         10.1.21-MariaDB - mariadb.org binary distribution
-- SO del servidor:              Win32
-- HeidiSQL Versión:             9.4.0.5125
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Volcando estructura para tabla plantillas.anosfiscales
CREATE TABLE IF NOT EXISTS `anosfiscales` (
  `idAnoFiscal` int(11) NOT NULL AUTO_INCREMENT,
  `nombreAnoFiscal` year(4) NOT NULL,
  PRIMARY KEY (`idAnoFiscal`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf16 COLLATE=utf16_spanish_ci;

-- Volcando datos para la tabla plantillas.anosfiscales: ~0 rows (aproximadamente)
DELETE FROM `anosfiscales`;
/*!40000 ALTER TABLE `anosfiscales` DISABLE KEYS */;
INSERT INTO `anosfiscales` (`idAnoFiscal`, `nombreAnoFiscal`) VALUES
	(1, '2017');
/*!40000 ALTER TABLE `anosfiscales` ENABLE KEYS */;

-- Volcando estructura para tabla plantillas.componentesfederales
CREATE TABLE IF NOT EXISTS `componentesfederales` (
  `idComponenteFederal` int(11) NOT NULL AUTO_INCREMENT,
  `nombreComponenteFederal` char(200) COLLATE utf16_spanish_ci NOT NULL DEFAULT '0',
  PRIMARY KEY (`idComponenteFederal`)
) ENGINE=InnoDB AUTO_INCREMENT=90007 DEFAULT CHARSET=utf16 COLLATE=utf16_spanish_ci;

-- Volcando datos para la tabla plantillas.componentesfederales: ~77 rows (aproximadamente)
DELETE FROM `componentesfederales`;
/*!40000 ALTER TABLE `componentesfederales` DISABLE KEYS */;
INSERT INTO `componentesfederales` (`idComponenteFederal`, `nombreComponenteFederal`) VALUES
	(1, 'MEJORAMIENTO PRODUCTIVO DE SUELO Y AGUA'),
	(272, 'CONSERVACIÓN Y USO SUSTENTABLE DEL SUELO Y EL AGUA'),
	(291, 'SISTEMA NACIONAL DE INFORMACIÓN PARA EL DESARROLLO RURAL SUSTENTABLE (SNIDRUS)'),
	(361, 'AGROINCENTIVOS'),
	(362, 'AGROPRUDUCCION INTEGRAL'),
	(363, 'DESARROLLO DE CLUSTER AGROALIMENTARIO (AGROCLUSTER)'),
	(364, 'PROAGRO PRODUCTIVO'),
	(365, 'PROCAFE E IMPULSO PRODUCTIVO AL CAFE'),
	(366, 'PRODUCCION INTENSIVA Y CUBIERTAS AGRICOLAS (PROCURA)'),
	(367, 'SISTEMAS PRODUCTO AGRICOLAS (SISPROA)'),
	(368, 'BIOENERGIA Y SUSTENTABILIDAD'),
	(369, 'RECONVERSION Y PRODUCTIVIDAD-APOYO A LOS PRODUCTORES DE MAIZ Y/O SORGO'),
	(371, 'INNOVACION PARA EL DESARROLLO TECNOLOGICO APLICADO (IDETEC) - MAQUINARIA'),
	(372, 'INNOVACION Y TRANSFERENCIA DE TECNOLOGIA GANADERA'),
	(373, 'RECURSOS GENETICOS ACUICOLAS'),
	(374, 'RECURSOS GENETICOS AGRICOLAS'),
	(375, 'RECURSOS ZOOGENETICOS'),
	(376, 'INNOVACION PARA EL DESARROLLO TEC. APLICADO (IDETEC) -ITT'),
	(391, 'IMPULSO A LA CAPITALIZACION PESQUERA Y ACUICOLA - MODERNIZACION DE EMBARCACIONES PESQUERAS(FLOTA MENOR)'),
	(392, 'OBRAS Y ESTUDIOS PARA EL MEJORAMIENTO DE LA PRODUCTIVDAD PESQUERA Y ACUICOLA - OBRAS Y ESTUDIOS'),
	(393, 'ENERGETICOS PESQUEROS Y ACUICOLA-DIESEL MARINO'),
	(394, 'INTEGRACION PRODUCTIVA Y COMERCIAL PESQUERA Y ACUICOLA - SISTEMAS PESQUEROS  Y ACUICOLAS'),
	(395, 'INTEGRACION PRODUCTIVA Y COMERCIAL PESQUERA Y ACUICOLA - TRANSFORMACION Y DESARROLLO DE PRODUCTOS PESQUEROS Y ACUICOLAS'),
	(396, 'INTEGRACION PRODUCTIVA Y COMERCIAL PESQUERA Y ACUICOLA - ADIESTRAMIENTO PESQUERO Y ACUICOLA'),
	(397, 'DESARROLLO ESTRATEGICO DE LA ACUACULTURA -  ACUACULTURA RURAL'),
	(398, 'DESARROLLO ESTRATEGICO DE LA ACUACULTURA - ACUACULTURA COMERCIAL EN AGUAS INTERIORES'),
	(399, 'DESARROLLO ESTRATEGICO DE LA ACUACULTURA - MEJORAMIENTO PRODUCTIVO DE EMBALSES'),
	(401, 'ENERGIA ELECTRICA DE USO DE RIEGO AGRICOLA'),
	(412, 'CERTIFICACION PARA LA PRODUCTIVIDAD AGROLIMENTARIA'),
	(413, 'DESARROLLO PRODUCTIVO DEL SUR SURESTE'),
	(415, 'PLANEACION DE PROYECTOS (MAPA DE PROYECTOS)'),
	(416, 'PRODUCTIVIDAD AGROLIMENTARIA'),
	(417, 'PROGRAMA REGIONAL DE DESARROLLO PREVISTO EN EL PND'),
	(418, 'SISTEMA NACIONAL DE AGROPARQUES'),
	(421, 'PROY.PRODUCTIVOS O ESTRATEGICOS AGRICOLA,PECUARIO,PESCA'),
	(431, 'MANEJO POSTPRODUCCION PECUARIA - INFRAESTRUCTURA, MAQUINARIA Y EQUIPO POSTPRODUCTIVO PECUARIO'),
	(432, 'PRODUCTIVIDAD PECUARIA - GANADO ALIMENTARIO'),
	(434, 'PROGRAMA DE PERFORACION Y EQUIPAMIENTO DE POZOS GANADEROS'),
	(436, 'BIOSEGURIDAD PECUARIA'),
	(438, 'INFRAESTRUCTURA Y EQUIPO DEL REPOBLAMIENTO'),
	(439, 'RECRIA PECUARIA'),
	(441, 'AGRICULTURA FAMILIAR, PERIURBANA Y DE TRASPATIO'),
	(444, 'DESARROLLO DE LAS ZONAS ARIDAS (PRODEZA)'),
	(445, 'DESARROLLO INTEGRAL DE CADENAS VALOR'),
	(446, 'EXTENSION E INNOVACION PRODUCTIVA (CEIP)'),
	(448, 'MODERNIZACION SUSTENTABLE DE LA AGRICULTURA TRADICIONAL (MASAGRO)'),
	(449, 'PROYECTO ESTRATEGICO DE SEGURIDAD ALIMENTARIA (PESA)'),
	(451, 'SANIDAD'),
	(452, 'INOCUIDAD'),
	(453, 'INSPECCION EN LA MOVILIZACION NACIONAL'),
	(461, 'SISTEMAS PRODUCTO AGRICOLAS (SISPROA)'),
	(2310, 'TECNIFICACION DEL RIEGO'),
	(2318, 'MINERIAL SOCIAL'),
	(3610, 'PROGRAMA DE INCENTIVOS PARA PRODUCTORES DE MAIZ Y FRIJOL (PIMAF)'),
	(3611, 'RECONVERSION Y PRODUCTIVIDAD - DE CULTIVOS DE MAIZ A SORGO O FRIJOL PINTO'),
	(3612, 'INCENTIVOS AL PAQUETE TECNOLOGICO DE LOS PRODUCTORES DE TRIGO CICLO OTOÑO-INVIERNO EN EL ESTADO DE SINALOA'),
	(3618, 'INCENTIVOS AL PAQUETE TECNOLÓGICO DE LOS PRODUCTORES DE CAÑA DE AZÚCAR  ( PARA PRODUCCIÓN DE AZÚCAR Y ETANOL ) 2014, ZAFRA 2013/2014'),
	(3910, 'DESARROLLO ESTRATEGICO DE LA ACUACULTURA - MARICULTURA'),
	(3912, 'ORDENAMIENTO PESQUERO Y ACUICOLA INTEGRAL Y SUSTENTABLE - DISMINUCION DEL ESFUERZO PESQUERO'),
	(3913, 'SOP. PARA LA VIGILANCIA DE LOS REC. PESQUEROS Y ACUICOLAS'),
	(3914, 'PROPESCA'),
	(3918, 'OBRAS Y ESTUDIOS PARA EL MEJORAMIENTO DE LA PRODUCTIVDAD PESQUERA Y ACUICOLA - OBRAS Y ESTUDIOS(INFRAESTRUCTURA Y EQUIPAMIENTO ELECTRICO PARA GRANJAS ACUICOLAS)'),
	(3919, 'ENERGETICOS PESQUEROS Y ACUICOLA - GASOLINA RIBERAÑA'),
	(3920, 'IMPULSO A LA CAPITALIZACION PESQUERA Y ACUICOLA - MODERNIZACION DE EMBARCACIONES PESQUERAS (FLOTA MAYOR)'),
	(4120, 'INFORMACION ESTADISTICA Y ESTUDIOS (SNIDRUS)'),
	(4310, 'REPOBLAMIENTO'),
	(4311, 'MANEJO POSTPRODUCCION PECUARIO - INCENTIVOS A LA POSTPRODUCCION PECUARIA'),
	(4312, 'PRODUCTIVIDAD PECUARIA - MANEJO DE GANADO'),
	(4313, 'PRODUCTIVIDAD PECUARIA - REPRODUCCION Y MATERIAL GENETICO PECUARIO'),
	(4410, 'VINCULACION CON ORGANISMOS DE LA SOCIEDAD CIVIL (OSC)'),
	(4411, 'EXTENSION E INNOVACION PRODUCTIVA (CEIP-DIRECTA)'),
	(90001, 'GASTOS DE OPERACIÓN'),
	(90002, 'GASTOS DE EVALUACIÓN'),
	(90004, 'GASTOS DE DIFUSION'),
	(90005, 'GASTOS PDI'),
	(90006, 'GASTOS DE SUPERVISION');
/*!40000 ALTER TABLE `componentesfederales` ENABLE KEYS */;

-- Volcando estructura para tabla plantillas.incentivosfederales
CREATE TABLE IF NOT EXISTS `incentivosfederales` (
  `idIncentivoFederal` int(11) NOT NULL AUTO_INCREMENT,
  `nombreIncentivoFederal` char(200) COLLATE utf16_spanish_ci NOT NULL DEFAULT '0',
  PRIMARY KEY (`idIncentivoFederal`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf16 COLLATE=utf16_spanish_ci;

-- Volcando datos para la tabla plantillas.incentivosfederales: ~1 rows (aproximadamente)
DELETE FROM `incentivosfederales`;
/*!40000 ALTER TABLE `incentivosfederales` DISABLE KEYS */;
INSERT INTO `incentivosfederales` (`idIncentivoFederal`, `nombreIncentivoFederal`) VALUES
	(1, 'SISTEMAS DE RIEGO TECNIFICADO');
/*!40000 ALTER TABLE `incentivosfederales` ENABLE KEYS */;

-- Volcando estructura para tabla plantillas.programasfederales
CREATE TABLE IF NOT EXISTS `programasfederales` (
  `idProgramaFederal` int(11) NOT NULL AUTO_INCREMENT,
  `nombreProgramaFederal` char(200) COLLATE utf16_spanish_ci NOT NULL DEFAULT '0',
  PRIMARY KEY (`idProgramaFederal`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf16 COLLATE=utf16_spanish_ci;

-- Volcando datos para la tabla plantillas.programasfederales: ~0 rows (aproximadamente)
DELETE FROM `programasfederales`;
/*!40000 ALTER TABLE `programasfederales` DISABLE KEYS */;
INSERT INTO `programasfederales` (`idProgramaFederal`, `nombreProgramaFederal`) VALUES
	(1, 'FOMENTO A LA AGRICULTURA');
/*!40000 ALTER TABLE `programasfederales` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
